### ISSUE TITLE
WorkbenchesApiClientTest failure

### ISSUE THREAD

**Issue by mcoumbes** [tenable/Tenable.io-SDK-for-Java#7]
I have the following test failure:
com.tenable.io.api.WorkbenchesApiClientTest > testVulnerabilities FAILED
    java.lang.AssertionError at WorkbenchesApiClientTest.java:31

These tests make assumptions that there is vulnerability data populated in the environment. In the case of a fresh environment there is none and these tests don't create any themselves.

Should we consider testing more generally that a valid result was returned without requiring it be populated with vulnerabilities similar to how the Python SDK tests are written?

**Comment by pierresc** [comment]
Michael, did you try again since last Thursday? We have relaxed some of the tests to accommodate for non-populated environment.

**Comment by pierresc** [comment]
Michael, the test fails on the first assert in this block of code:
`        List<ScanVulnerability> result = apiClient.getWorkbenchesApi().vulnerabilities( new ExtendedFilteringOptions() );
        if(result != null && result.size() > 0) {
            assertNotNull(result.get(0));
            assertTrue(result.get(0).getPluginId() > 0);
            assertTrue(result.get(0).getSeverity() > 0);
        }`
This is odd because I now make sure the result.size() is greater then 0 before trying to assert the first element is not null so I assume the API actually returns a null element? Do you mind running with a web proxy and sending me the API request/response?

**Comment by mcoumbes** [comment]
I am not able to reproduce this test failure now. It may have had something to do with my test environment at the time and I don't still have the proxy capture from then. Closing this issue.
